version: "3.9"
services:
  # development local database
  task_db:
    container_name: task_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_db
    ports:
      - "5432:5432"
  # test local database (non-persistent)
volumes:
   task_db:
    driver: local
